//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhridCityPassClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public int TourId { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public Nullable<int> isTaken { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
