//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhridCityPassClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Price_FirstName
    {
        public int OrderID { get; set; }
        public Nullable<decimal> Expr1 { get; set; }
        public string FirstName { get; set; }
    }
}
